spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/gsc_order_manager?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false
app.security.jwt.secret=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
app.security.jwt.access-token-expiration-ms=3600000
app.security.default-admin.email=admin@gsc.local
app.security.default-admin.password=Admin@123
app.security.default-admin.full-name=System Administrator
app.security.default-admin.department=Administration
